FROM node:25
# Create app directory
WORKDIR /parent/server
COPY ./server/package*.json ./
RUN npm install
# If you are building your code for production
# RUN npm ci --omit=dev
# Bundle app source
COPY ./server .
EXPOSE 5000
CMD [ "npm", "run", "dok"]